image: ruby:2.3

before_script:
  - apt-get update > /dev/null
  - apt-get install -y locales
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8

pages:
  script:
      # TODO: once jekyll-redirect-from is fixed, update jekyll
      # @see https://github.com/jekyll/jekyll/issues/6154
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install jekyll-paginate
  - gem install jekyll-feed
  - gem install jekyll-redirect-from
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
