name: "Nate Levesque"
blogname: "The Philosophy of Nate"
description: ""

url: "https://www.thenaterhood.com"
# URL for open-graph things which appear not
# to get along with https
og_url: "http://www.thenaterhood.com"
paginate: 10
paginate_path: "/blog/archive-:num"
#permalink: pretty
permalink: "/blog/read/:year.:month.:day.htm/"
# WARNING: This is a javascript redirect.
# It is not nearly as secure a true server
# setup. You have been warned.
redirect_to_https: yes

highligher: pygments

gems:
        - jekyll-sitemap
        - jekyll-paginate
        - jekyll-feed
        - jekyll-redirect-from
