name: "Nate Levesque"
blogname: "The Philosophy of Nate"
description: ""

url: "www.thenaterhood.com"
paginate: 10
paginate_path: "/blog/archive-:num"
#permalink: pretty
permalink: "/blog/read/:year.:month.:day.htm"

markdown: rdiscount
pygments: true

gems:
        - jekyll-sitemap
