name: "Nate Levesque"
description: ""

url: "www.thenaterhood.com"
paginate: 10
paginate_path: "/blog/page:num"
#permalink: pretty
permalink: "/blog/read/:year.:month.:day.htm"

markdown: rdiscount
pygments: true
