name: "Nate Levesque"
blogname: "The Philosophy of Nate"
description: ""

url: "http://www.thenaterhood.com"
paginate: 10
paginate_path: "/blog/archive-:num"
#permalink: pretty
permalink: "/blog/read/:year.:month.:day.htm"

highligher: pygments

gems:
        - jekyll-sitemap
        - jekyll-paginate
        - jekyll-feed
